#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }
#
#constraint:
#  path: /{param}/
#  defaults: { _controller: AppBundle:Default:paramConstraint }
#  requirements:
#    param: '\d+'
#
#param_homepage:
#  path: /{param}/
#  defaults: { _controller: AppBundle:Default:param }

request_querystring:
  path: /querystring/
  defaults: { _controller: AppBundle:Default:requestQuerystring }

request_post:
  path: /post/
  defaults: { _controller: AppBundle:Default:requestPost }
  methods: [POST]

calculator_index:
  path: /calculator/
  defaults: { _controller: AppBundle:Calculator:index }
  methods: [GET]

calculator_add:
  path: /calculator/add/{param1}/{param2}/
  defaults: { _controller: AppBundle:Calculator:add }
  methods: [GET]

calculator_subtract:
    resource: "@AppBundle/Controller/CalculatorController.php"
    type: annotation

calculator_multiply:
  path: /calculator/multiply/{param1}/
  defaults: { _controller: AppBundle:Calculator:multiply }
  methods: [GET]

calculator_divide:
  path: /calculator/divide/
  defaults: { _controller: AppBundle:Calculator:divide }
  methods: [POST]
